travis:
  secure:
    BINSTAR_TOKEN: kUMqpYy/j/QI+HPYP3oCfCIwbTuPgjZWbAANctkYE9Rnpa/7v00jhbHfpuoKvpJdoTC0cGh5tOTvFPd3ViCxSfp2KMyQTcVq0B+FYs+PXgvuNxN6pngHTU58t7OXlRk2pyb9DjhHngxllhX6ZVRj6sSaI99Iopv/qM4pD/8D70nTe8qYzWQkYkeTJDUSUljCbrCtt3RzjqElpEXcjdteoLU7gMRjL9J0klDwwJGiVErlaXLgCFVu1/TU7KrGHzMCHGIbstBCX2gsTyDvR0/dtHV7wSLwdfMC2WMG7yrKkqim6xpyf6mrWBpbnyMqdFizyyFV3bSk7gERymKBTZhq9BepoqdzpZlp8rTl03/VELngEzGiQdDTdbTNp+LFq5paGXp7t4hg5WRnCsIW0GpwTcfFvhV7vpTizfAsjuz5G46OUEhkVnQhm7z95hJYZ476lvDt6UIZJdPYpRkxqJEhT9eXzJQ+X52GslVWN7sgo1D2zJzzibsvlG1XER8tdhGKEox8BejBZMb8/nmmfymvCpYKhpqW9pqjpf1Ssz6/vV9OrkEGdZIhOB412lJAR0JtQ64njGLRAayEhbpxumZRwcJzl2ATM++eWRtn1XDxADAD5501iTsovhh0UjqEAd08S7+XGUSHCr4nznkbnOFa+BJuiXfOSfphFSB8H+pIfoM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
