travis:
  secure:
    BINSTAR_TOKEN: ir1lEGhDdOz/iSb/6bPfJPiYg4vjQV48QYwi+WhBqENclWuKpPAqHTpKEP53NVD16eCPhOT12UZkXPsFMNlWZ3xBq2kO2sk4cBlJXdoHs8T/hiQ1i/u2uewFsuKkv2tOZhoEEeRWTUS7moFtSM0c9+lnTSD7hiPU6JsgJ6KY2WBocYMU53ZphxtaJCoVIjpjsP0LW1DDIkTu7Z+IE9qX+caQq8AoDDWfYVPPhet8CMn4f8xjXvrJOZ7XhMyb7XXcGwsdE1Nl6quM3sb6NN6DAD5NB72mhHlHxLVvNQ7y/FaSAWz7WjSG4F2YNn7L3h5EEL/Lr15YNbMDXB0Kf2S11xsQvjqsLX7/ROCR/vp4jP1E23CejQhhVoiM8qXCTDAhfJfMMxuJ6mfWaRiu46tj+ry67E75r+OYiey86TpNeRTL9UCx1GO/d3mNpAhkrhJVk6ZlcY7+chAKOjNMAXNosznq1AhOYTgq85WbVL6ZVLeU9Gh0RaAi5Qgii6UcXhgZR0poGuccSCY0WmYRO/7OyTXsz3hXq3E+moLB3I8Z64eiIdiVaDssT6o47MPfRPbfVOmVtBj2721YK5gTFqp3IeHeUkLakBIzsJueXD0z9UvUUpo4B2LsF1zKYZrxn6TFG+ZfyDVs+oU5gjR8jhF3wyViu4UKsO6ZA/ne93qIfyk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
