travis:
  secure:
    BINSTAR_TOKEN: OBxz5tndImoeP78980wfp+Jj8ODhc+fOd6O2PeoZ1vF60xX2f7WgSztfTAkETBSrU22+q633MTq/iSXqmMurhSdQo4+NemdOxjkLlxr+6ICU9u1kiUPDlO+Fu578FveDkn0r+X9Up9dZcF5dROmrmvUZkRkmvwTWVSeHgI8rjn9ih0rKdYymd0h79qudXK6TEm1YjVxFrI06Zp/e+hkG3OIMnuk5vR1yb95+DB31vd/NPEMjsC7s2s1thH5/wfx15YWcpah+7JXnVOZj5s2e+/YETjym63oHF+eecVBh/oOBeFjvYWXLssA4TRwZQ3687aUHzCZ9jr3QAcox3xhHUGs2QVKMqtKke8DaIMmQntKxdTczYVMgJWjvx2SdyL/9qlsjCYw4i+T3JlbBhHC0JO1QVVzRbeExHZW47qBRfpyN7Y5us+85t9O/LqrWIz4JY2LalQPV0Eg0Z56YwV5L49Blw8MrofzbjgeAZ9s+jgzRJ11o+t8TGtjYfTAINiX3WqJ5KKP3rso7p+tdoAh0mCinS1Kc8ColTPDBrCNpve4iFHm2+ewt+i+SP1ZzYxDxFWl6c8uj0AtCtuxHO+AKYSWd45LCxRJyt/kRBBxdDZslhg+196QWCEOwd6IIO3c8YAYfUgy9/XJSfGmOrsDcRv+/oB05tT/QLXuX5SZBNuo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
